### ISSUE TITLE
mrtrix: resolution of input-output pair paths

### ISSUE THREAD

**Issue by kaitj** [childmindresearch/niwrap#116]
For commands using lists of input / output pairs (e.g. [dwi2fod](), [mtnormalise]()), path resolution is currently an issue (sorry @nx10 - words are escaping me but we chatted about this 😅).

**Comment by nx10** [comment]
Should be fixed with https://github.com/childmindresearch/niwrap/commit/16c8c67de8ad668218761442a8f704c7399e64ce
